language: node_js
node_js:
- '8'
before_script:
- npm i -g mocha
- mocha --version
env:
  matrix:
    secure: eXmu7hxgn6cmOXBnB+1A7gVxiYtQD8/w5Ue2c9g5oE4UXyPcq9fv0slSeWR2ejHmV/HGGD8fVORhP2rP0NWMItUCDncrxyPgOb2/ZBqYxQ0NIDFJgkVZ0xHwFbfm/lImTF1JUYIpZ6W6x/IbvJUef4O1EmgAH4jPE9n+ZbO73Zmu13vsQEFyy/BrilSKTdsXFZ2qCNum0es2CQqCkPDKmUZDRO09GEFpy/N9hxhfRGozC6dmbcC0kW1KURqdZZE8K2XesHTYWLtfldBzb968MF4n4SGn2VcTkeOUiA1w7DQMjq21XhFE+qMt9OkpEzsAgPigNmcjVg4q1PKpTzw+FN4jR9lvZ5rrIdfrXiNQT0EZA/xMCe9Qag1VQZzpD2ylYCGqINKORsjVrd4IWl3t5ZCI28AYI2inIwsWfTSabjk88tB4CFfX2JlAtbalXPxIwPOSJNvTYzaEpnITlJILlO5FQkGVt3TNXR1zqGBQmcS4M3Q3YMr4B3Cy8OLdB/Pzb590SwSZ+A0AbrJt/HUsRBXNah2qzD6qoAaQxna8s7Y4IPnhCXPt031wKnrPgqluwJo7/cob+A3g1Dku5l9OxTU8ITK2cn82HoXxLqIQND3ZT4y69mFkxzjY+99HAokCOXEcu3G2jOhX+1nCMxC30G+2UrjGlNUnM3W9ajX9V+4=
